class Employee {
  constructor(
    PLA_COMPANY_ID,
    COMPANY_NAME,
    COMPANY_WEBSITE,
    ESTABLISHED_IN,
    TURNOVER,
    ENTRY_DATE,
    COMPANY_ADDRESS,
    HIRING_SINCE,
    NO_OF_EMPLOYEES
  ) {
    this.PLA_COMPANY_ID = PLA_COMPANY_ID;
    this.COMPANY_NAME = COMPANY_NAME;
    this.COMPANY_WEBSITE = COMPANY_WEBSITE;
    this.ESTABLISHED_IN = ESTABLISHED_IN;
    this.TURNOVER = TURNOVER;
    this.ENTRY_DATE = ENTRY_DATE;
    this.COMPANY_ADDRESS = COMPANY_ADDRESS;
    this.HIRING_SINCE = HIRING_SINCE;
    this.NO_OF_EMPLOYEES = NO_OF_EMPLOYEES;
  }
}

module.exports = Employee;
