class Employee {
  constructor(
    PLACEMENT_REQUIREMENT_TYPE_ID,
    REQUIREMENT_NAME,
    REQUIREMENT_SHORT_NAME,
    ACTIVE,
    DELETED,
    ENTRY_USER_ID,
    ENTRY_DATE,
    UPDATE_USER_ID,
    LAST_UPDATE_DATE
  ) {
    this.PLACEMENT_REQUIREMENT_TYPE_ID = PLACEMENT_REQUIREMENT_TYPE_ID;
    this.REQUIREMENT_NAME = REQUIREMENT_NAME;
    this.REQUIREMENT_SHORT_NAME = REQUIREMENT_SHORT_NAME;
    this.ACTIVE = ACTIVE;
    this.DELETED = DELETED;
    this.ENTRY_USER_ID = ENTRY_USER_ID;
    this.ENTRY_DATE = ENTRY_DATE;
    this.UPDATE_USER_ID = UPDATE_USER_ID;
    this.LAST_UPDATE_DATE = LAST_UPDATE_DATE;
  }
}

module.exports = Employee;
